const checkout='SEU_LINK_CHECKOUT_HOTMART_AQUI';
document.querySelectorAll('.hotmart-link').forEach(a=>{ if(a.getAttribute('href')===checkout){ a.addEventListener('click',e=>{ if(checkout.includes('SEU_LINK')){ e.preventDefault(); alert('Antes de publicar, troque SEU_LINK_CHECKOUT_HOTMART_AQUI pelo link real do checkout da Hotmart dentro do index.html.'); } }); }});
const glow=document.querySelector('.cursor-glow');
window.addEventListener('pointermove',e=>{glow.style.left=e.clientX+'px';glow.style.top=e.clientY+'px'});
const obs=new IntersectionObserver((entries)=>{entries.forEach(en=>{if(en.isIntersecting){en.target.classList.add('visible');obs.unobserve(en.target)}})},{threshold:.12});
document.querySelectorAll('.reveal').forEach(el=>obs.observe(el));
const counts=document.querySelectorAll('[data-count]');
const countObs=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(!entry.isIntersecting)return;const el=entry.target;const max=+el.dataset.count;let cur=0;const step=Math.max(1,Math.ceil(max/55));const timer=setInterval(()=>{cur+=step;if(cur>=max){cur=max;clearInterval(timer)}el.textContent=cur+(max===100?'':'')},22);countObs.unobserve(el)})},{threshold:.5});counts.forEach(el=>countObs.observe(el));
document.querySelectorAll('[data-tilt]').forEach(card=>{card.addEventListener('mousemove',e=>{const r=card.getBoundingClientRect();const x=(e.clientX-r.left)/r.width-.5;const y=(e.clientY-r.top)/r.height-.5;card.style.transform=`perspective(1000px) rotateY(${x*10-13}deg) rotateX(${-y*8+4}deg) translateY(-8px)`});card.addEventListener('mouseleave',()=>card.style.transform='')});
document.querySelector('.menu-btn')?.addEventListener('click',()=>{const nav=document.querySelector('.nav');nav.style.display=nav.style.display==='flex'?'none':'flex';nav.style.position='fixed';nav.style.top='78px';nav.style.left='0';nav.style.right='0';nav.style.padding='20px';nav.style.flexDirection='column';nav.style.background='rgba(8,10,31,.96)'});
